baseURL = "https://covid.molssi.org/"
languageCode = "en-us"
title = "COVID-19 Molecular Structure and Therapeutics Hub"
theme = "minimal"
# disqusShortname = "username" # delete this to disable disqus comments
# googleAnalytics = ""

# Additional custom parameters
# Ignore README files meant for GitHub
ignoreFiles = ["README.md$"]

[params]
    author = "MolSSI and BioExcel"
    description = "Aggregating critical information to accelerate drug discovery for the molecular modeling and simulation community."
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/targets"
    name = "Targets"
    weight = 2

[[menu.main]]
    url = "/proteins/"
    name = "Proteins"
    weight = 3

[[menu.main]]
    url = "/structures"
    name = "Structures"
    weight = 4

[[menu.main]]
    url = "/simulations/"
    name = "Simulations"
    weight = 8

[[menu.main]]
    url = "/models"
    name = "Models"
    weight = 6

[[menu.main]]
    url = "/therapeutics"
    name = "Therapeutics"
    weight = 7

[[menu.main]]
    hasChildren = true
    name = "Contributions"
    weight = 9
    
    [[menu.main]]
        parent = "Contributions"
        url = "/contributing/"
        name = "Contributing"
        weight = 1
        
    [[menu.main]]
        parent = "Contributions"
        url = "/contributors/"
        name = "Contributors"
        weight = 2

[[menu.main]]
    hasChildren = true
    name = "About & Links"
    weight = 600

    [[menu.main]]
        parent = "About & Links"
        url = "/about/"
        name = "About the Hub"
        weight = 1

    [[menu.main]]
        parent = "About & Links"
        url = "/collaborating/"
        name = "Collaborating"
        weight = 2

    [[menu.main]]
        parent = "About & Links"
        url = "/links/"
        name = "External Resources"
        weight = 3

    [[menu.main]]
        parent = "About & Links"
        url = "/glossary/"
        name = "Glossary"
        weight = 800
        
#    [[menu.main]]
#        parent = "About"
#        url = "/teams/"
#        name = "Teams"
#        weight = 3

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "https://github.com/molssi/covid"
    name = "github"
    weight = 1

[[menu.icon]]
    url = "mailto:info@molssi.org"
    name = "envelope-o"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/MolSSI_NSF/"
    name = "twitter"
    weight = 3

