name: Schema Validation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    env:
      PYVER: 3.8
      CI_OS: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Additional info about the build
      shell: bash
      run: |
        uname -a
        df -h
        ulimit -a

    - name: Create environment for package
      shell: bash
      run: |
        . repo_management/github-actions/initialize_conda.sh
        conda activate
        conda info
        conda create -n schema python==$PYVER pyyaml pydantic

    - name: Run Schema Validation
      shell: bash
      run: |
        . repo_management/github-actions/initialize_conda.sh
        conda activate schema
        cd schema
        python validation.py
